### PR TITLE
Onboard Jani, uplift Seb

### PR DESCRIPTION
**Pull request by paroxp**

### CODE REVIEW

**Review by LeePorte — CHANGES_REQUESTED** [review]
No GPG key for Jani on this PR

**Comment by paroxp** [comment]
Do we expect Jani to modify/merge this repository?

**Comment by LeePorte** [comment]
It's certainly possible.

**Comment by LeePorte** [comment]
Needs a `make update_merge_keys`

**Review by kr8n3r — APPROVED** [review]

**Pull request merged**
