### PR TITLE
Add boostrap concourse ssh target

### PR DESCRIPTION
**Pull request by mtekel**
## What

Add makefile target to ssh to bootstrap concourse. Display bootstrap concourse IP in showenv.

## How to review

Deploy your bootstrap server if you don't have one already. Run `make dev ssh_bootstrap_concourse`. 
Run `make dev showenv`. Check that the it also contains bootstrap concourse IP.

## Who can review

not @mtekel

### CODE REVIEW

**Comment by alext** [comment]
I don't think this change is correct. I expect these two cases to operate on the concourse that this repo creates (ie the deployer/build concourse).

If we want to add tasks to access the temporary bootstrap concourse, then these should be added separately IMO.

**Comment by mtekel** [comment]
updated

**Comment by combor** [comment]
@alext I agree that we we should have separate tasks for ssh-ing to deployer and bootstrap Concourse. What I'm not sure about is where to put them but IMO we should avoid code duplication. Now we've got `ssh_concourse` target in `paas-bootstrap` and `paas-cf` but not in `paas-release-ci`. So I would got for either:
- centralise ssh_concourse in `paas-bootstrap` or
- implement `ssh_concourse` in `paas-release-ci` and remove from `paas-bootstrap`

**Comment by mtekel** [comment]
Agreed, but looks a bit out of scope of this PR. We have a story for that kind of things: https://www.pivotaltracker.com/story/show/137365155

**Pull request merged**
