### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by 0atman**
What
----

Updated the readme with little fixes I needed for my own install.

How to review
-------------

Someone who knows the setup should sanity check my changes

Who can review
--------------

Any paaser

---

🚨⚠️ Please do not merge this pull request via the GitHub UI ⚠️🚨

### CODE REVIEW

**Review by AP-Hunt — COMMENTED** [review]
It's worth setting `AWS_DEFAULT_REGION` in your shell regardless, because your dev env will be in either London or Ireland.

**Comment by 0atman** [comment]
@AP-Hunt thanks Andy, which should be the default, LON or IE?

**Comment by AP-Hunt** [comment]
Doesn't matter, really. We have a mix, I think. Pick the place you like most 🤷‍♂️

**Review by schmie — APPROVED** [review]
Comments addressed, changes are sensible.

**Comment by schmie** [comment]
Superseded by https://github.com/alphagov/paas-bootstrap/pull/482

**Pull request closed without merging**
