### PR TITLE
Upgrade concourse to 6.0.0

### PR DESCRIPTION
**Pull request by LeePorte**
What
----

We need to keep up with the times, so this upgrades concourse to the latest version

How to review
-------------

Code review and deploy to dev (2 runs of create-bosh-concourse are required)

Who can review
--------------

Anyone

### CODE REVIEW

**Review by tlwr — APPROVED** [review]
Having it stop at `concourse-deploy` and then starting `init-pipeline` worked for me

**Review by paroxp — APPROVED** [review]
Looks good in general.

There is one problem I'm noticing...

If I try to start the job somewhere in the middle of the pipeline, (the original trigger not the new one) it will not start...

It does however work fine, running from beginning. Change of habit I suppose. Would either of you attempt to replicate that issue and decide if it's legit blocker or not?

**Comment by tlwr** [comment]
I think this is an intended change in behaviour in Concourse and you have to use the new "trigger with same inputs" button - or pin the resource

**Comment by LeePorte** [comment]
Correct, this is a change in behaviour with the new algorithm introduced https://github.com/concourse/concourse/releases/tag/v6.0.0

**Comment by paroxp** [comment]
Figured. Just so we're aware :) Merge away!

**Pull request merged**
