### PR TITLE
[#169336585]Update AWS RDS CA certificate bundle

### PR DESCRIPTION
**Pull request by AP-Hunt**
What
----
On 2020-03-05, the current CA certs for AWS RDS will expire. This commit
updates the bundle we use to include the new certificates which will become the
default for new databases as of 2019-11-01.

The bundle was obtained from
https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem on
2019-10-28.

How to review
-------------
See the review instructions on https://github.com/alphagov/paas-cf/pull/2121

Also run it down your dev env

Who can review
--------------
Anyone

### CODE REVIEW

**Comment by tlwr** [comment]
I downloaded the bundle and added it in-place and saw no diff.

I ran:

```
sdiff -w 200 <(openssl crl2pkcs7 -nocrl -certfile <(git show wip-tlwr:manifests/bosh-manifest/variables.yml  | boshfind -f - /aws_rds_combined_ca_bundle | tr -s '[[:space:]]' | sed 's/^ //' | tr -d "'" | grep .) | openssl pkcs7 -print_certs -text | grep -e keyid -e After) <(openssl crl2pkcs7 -nocrl -certfile <(git show master:manifests/bosh-manifest/variables.yml  | boshfind -f - /aws_rds_combined_ca_bundle | tr -s '[[:space:]]' | sed 's/^ //' | tr -d "'" | grep .) | openssl pkcs7 -print_certs -text | grep -e keyid -e After)
```

to verify that only certs were appended:

```
            Not After : Mar  5 09:11:31 2020 GMT							            Not After : Mar  5 09:11:31 2020 GMT
                keyid:4E:02:EE:AC:3E:F6:15:C8:4C:ED:2C:F5:05:C1:8F:9C:84:08:49:83			                keyid:4E:02:EE:AC:3E:F6:15:C8:4C:ED:2C:F5:05:C1:8F:9C:84:08:49:83
            Not After : Mar  5 22:03:06 2020 GMT							            Not After : Mar  5 22:03:06 2020 GMT
                keyid:4E:02:EE:AC:3E:F6:15:C8:4C:ED:2C:F5:05:C1:8F:9C:84:08:49:83			                keyid:4E:02:EE:AC:3E:F6:15:C8:4C:ED:2C:F5:05:C1:8F:9C:84:08:49:83
            Not After : Mar  5 22:03:19 2020 GMT							            Not After : Mar  5 22:03:19 2020 GMT
                keyid:4E:02:EE:AC:3E:F6:15:C8:4C:ED:2C:F5:05:C1:8F:9C:84:08:49:83			                keyid:4E:02:EE:AC:3E:F6:15:C8:4C:ED:2C:F5:05:C1:8F:9C:84:08:49:83
            Not After : Mar  5 22:03:24 2020 GMT							            Not After : Mar  5 22:03:24 2020 GMT
                keyid:4E:02:EE:AC:3E:F6:15:C8:4C:ED:2C:F5:05:C1:8F:9C:84:08:49:83			                keyid:4E:02:EE:AC:3E:F6:15:C8:4C:ED:2C:F5:05:C1:8F:9C:84:08:49:83
            Not After : Mar  5 22:03:31 2020 GMT							            Not After : Mar  5 22:03:31 2020 GMT
                keyid:4E:02:EE:AC:3E:F6:15:C8:4C:ED:2C:F5:05:C1:8F:9C:84:08:49:83			                keyid:4E:02:EE:AC:3E:F6:15:C8:4C:ED:2C:F5:05:C1:8F:9C:84:08:49:83
            Not After : Mar  5 22:03:35 2020 GMT							            Not After : Mar  5 22:03:35 2020 GMT
                keyid:4E:02:EE:AC:3E:F6:15:C8:4C:ED:2C:F5:05:C1:8F:9C:84:08:49:83			                keyid:4E:02:EE:AC:3E:F6:15:C8:4C:ED:2C:F5:05:C1:8F:9C:84:08:49:83
            Not After : Mar  5 22:03:40 2020 GMT							            Not After : Mar  5 22:03:40 2020 GMT
                keyid:4E:02:EE:AC:3E:F6:15:C8:4C:ED:2C:F5:05:C1:8F:9C:84:08:49:83			                keyid:4E:02:EE:AC:3E:F6:15:C8:4C:ED:2C:F5:05:C1:8F:9C:84:08:49:83
            Not After : Mar  5 21:54:04 2020 GMT							            Not After : Mar  5 21:54:04 2020 GMT
                keyid:4E:02:EE:AC:3E:F6:15:C8:4C:ED:2C:F5:05:C1:8F:9C:84:08:49:83			                keyid:4E:02:EE:AC:3E:F6:15:C8:4C:ED:2C:F5:05:C1:8F:9C:84:08:49:83
            Not After : Mar  5 22:03:45 2020 GMT							            Not After : Mar  5 22:03:45 2020 GMT
                keyid:4E:02:EE:AC:3E:F6:15:C8:4C:ED:2C:F5:05:C1:8F:9C:84:08:49:83			                keyid:4E:02:EE:AC:3E:F6:15:C8:4C:ED:2C:F5:05:C1:8F:9C:84:08:49:83
            Not After : Mar  5 22:03:50 2020 GMT							            Not After : Mar  5 22:03:50 2020 GMT
                keyid:4E:02:EE:AC:3E:F6:15:C8:4C:ED:2C:F5:05:C1:8F:9C:84:08:49:83			                keyid:4E:02:EE:AC:3E:F6:15:C8:4C:ED:2C:F5:05:C1:8F:9C:84:08:49:83
            Not After : Mar  5 00:05:46 2020 GMT							            Not After : Mar  5 00:05:46 2020 GMT
                keyid:4E:02:EE:AC:3E:F6:15:C8:4C:ED:2C:F5:05:C1:8F:9C:84:08:49:83			                keyid:4E:02:EE:AC:3E:F6:15:C8:4C:ED:2C:F5:05:C1:8F:9C:84:08:49:83
            Not After : Mar  5 21:29:22 2020 GMT							            Not After : Mar  5 21:29:22 2020 GMT
                keyid:4E:02:EE:AC:3E:F6:15:C8:4C:ED:2C:F5:05:C1:8F:9C:84:08:49:83			                keyid:4E:02:EE:AC:3E:F6:15:C8:4C:ED:2C:F5:05:C1:8F:9C:84:08:49:83
            Not After : Mar  5 19:58:45 2020 GMT							            Not After : Mar  5 19:58:45 2020 GMT
                keyid:4E:02:EE:AC:3E:F6:15:C8:4C:ED:2C:F5:05:C1:8F:9C:84:08:49:83			                keyid:4E:02:EE:AC:3E:F6:15:C8:4C:ED:2C:F5:05:C1:8F:9C:84:08:49:83
            Not After : Mar  5 00:10:11 2020 GMT							            Not After : Mar  5 00:10:11 2020 GMT
                keyid:4E:02:EE:AC:3E:F6:15:C8:4C:ED:2C:F5:05:C1:8F:9C:84:08:49:83			                keyid:4E:02:EE:AC:3E:F6:15:C8:4C:ED:2C:F5:05:C1:8F:9C:84:08:49:83
            Not After : Mar  5 17:44:42 2020 GMT							            Not After : Mar  5 17:44:42 2020 GMT
                keyid:4E:02:EE:AC:3E:F6:15:C8:4C:ED:2C:F5:05:C1:8F:9C:84:08:49:83			                keyid:4E:02:EE:AC:3E:F6:15:C8:4C:ED:2C:F5:05:C1:8F:9C:84:08:49:83
            Not After : Mar  5 21:39:26 2020 GMT							            Not After : Mar  5 21:39:26 2020 GMT
                keyid:4E:02:EE:AC:3E:F6:15:C8:4C:ED:2C:F5:05:C1:8F:9C:84:08:49:83			                keyid:4E:02:EE:AC:3E:F6:15:C8:4C:ED:2C:F5:05:C1:8F:9C:84:08:49:83
            Not After : Mar  5 00:55:42 2020 GMT							            Not After : Mar  5 00:55:42 2020 GMT
                keyid:4E:02:EE:AC:3E:F6:15:C8:4C:ED:2C:F5:05:C1:8F:9C:84:08:49:83			                keyid:4E:02:EE:AC:3E:F6:15:C8:4C:ED:2C:F5:05:C1:8F:9C:84:08:49:83
            Not After : Mar  4 22:42:27 2020 GMT							            Not After : Mar  4 22:42:27 2020 GMT
                keyid:4E:02:EE:AC:3E:F6:15:C8:4C:ED:2C:F5:05:C1:8F:9C:84:08:49:83			                keyid:4E:02:EE:AC:3E:F6:15:C8:4C:ED:2C:F5:05:C1:8F:9C:84:08:49:83
            Not After : Mar  5 17:34:52 2020 GMT							            Not After : Mar  5 17:34:52 2020 GMT
                keyid:4E:02:EE:AC:3E:F6:15:C8:4C:ED:2C:F5:05:C1:8F:9C:84:08:49:83			                keyid:4E:02:EE:AC:3E:F6:15:C8:4C:ED:2C:F5:05:C1:8F:9C:84:08:49:83
            Not After : Jun  1 12:00:00 2022 GMT							            Not After : Jun  1 12:00:00 2022 GMT
                keyid:AF:53:EA:C6:3F:3C:16:55:6E:71:DC:35:C4:17:7F:9F:0F:E0:EB:8F			                keyid:AF:53:EA:C6:3F:3C:16:55:6E:71:DC:35:C4:17:7F:9F:0F:E0:EB:8F
            Not After : Feb 16 02:46:11 2024 GMT							            Not After : Feb 16 02:46:11 2024 GMT
                keyid:AF:53:EA:C6:3F:3C:16:55:6E:71:DC:35:C4:17:7F:9F:0F:E0:EB:8F			                keyid:AF:53:EA:C6:3F:3C:16:55:6E:71:DC:35:C4:17:7F:9F:0F:E0:EB:8F
            Not After : Jun  1 12:00:00 2025 GMT							            Not After : Jun  1 12:00:00 2025 GMT
                keyid:E7:87:1F:0E:38:30:07:1E:32:70:11:FC:FB:FA:FC:59:77:5A:8A:A6			                keyid:E7:87:1F:0E:38:30:07:1E:32:70:11:FC:FB:FA:FC:59:77:5A:8A:A6
            Not After : May  8 21:48:27 2024 GMT							            Not After : May  8 21:48:27 2024 GMT
                keyid:E7:87:1F:0E:38:30:07:1E:32:70:11:FC:FB:FA:FC:59:77:5A:8A:A6			                keyid:E7:87:1F:0E:38:30:07:1E:32:70:11:FC:FB:FA:FC:59:77:5A:8A:A6
            Not After : Aug 19 17:38:26 2024 GMT							            Not After : Aug 19 17:38:26 2024 GMT
                keyid:AD:A1:0C:15:A5:B1:B1:F3:B7:F1:07:77:44:18:3A:8A:2A:70:53:E1			                keyid:AD:A1:0C:15:A5:B1:B1:F3:B7:F1:07:77:44:18:3A:8A:2A:70:53:E1
            Not After : Aug 19 17:38:26 2024 GMT							            Not After : Aug 19 17:38:26 2024 GMT
                keyid:AD:A1:0C:15:A5:B1:B1:F3:B7:F1:07:77:44:18:3A:8A:2A:70:53:E1			                keyid:AD:A1:0C:15:A5:B1:B1:F3:B7:F1:07:77:44:18:3A:8A:2A:70:53:E1
            Not After : Aug 21 22:29:49 2024 GMT							            Not After : Aug 21 22:29:49 2024 GMT
                keyid:69:D3:1A:94:2E:43:61:FF:0D:99:57:31:08:A3:64:48:63:B3:B4:DD			                keyid:69:D3:1A:94:2E:43:61:FF:0D:99:57:31:08:A3:64:48:63:B3:B4:DD
            Not After : Aug 21 22:29:49 2024 GMT							            Not After : Aug 21 22:29:49 2024 GMT
                keyid:69:D3:1A:94:2E:43:61:FF:0D:99:57:31:08:A3:64:48:63:B3:B4:DD			                keyid:69:D3:1A:94:2E:43:61:FF:0D:99:57:31:08:A3:64:48:63:B3:B4:DD
            Not After : Aug 22 17:08:50 2024 GMT							            Not After : Aug 22 17:08:50 2024 GMT
                keyid:73:5F:60:D8:BC:CB:03:98:F4:2B:17:34:2E:36:5A:A6:60:FF:BC:1F			                keyid:73:5F:60:D8:BC:CB:03:98:F4:2B:17:34:2E:36:5A:A6:60:FF:BC:1F
            Not After : Aug 22 17:08:50 2024 GMT							            Not After : Aug 22 17:08:50 2024 GMT
                keyid:73:5F:60:D8:BC:CB:03:98:F4:2B:17:34:2E:36:5A:A6:60:FF:BC:1F			                keyid:73:5F:60:D8:BC:CB:03:98:F4:2B:17:34:2E:36:5A:A6:60:FF:BC:1F
            Not After : Aug 22 17:08:50 2024 GMT							            Not After : Aug 22 17:08:50 2024 GMT
                keyid:73:5F:60:D8:BC:CB:03:98:F4:2B:17:34:2E:36:5A:A6:60:FF:BC:1F			                keyid:73:5F:60:D8:BC:CB:03:98:F4:2B:17:34:2E:36:5A:A6:60:FF:BC:1F
            Not After : Aug 22 17:08:50 2024 GMT							            Not After : Aug 22 17:08:50 2024 GMT
                keyid:73:5F:60:D8:BC:CB:03:98:F4:2B:17:34:2E:36:5A:A6:60:FF:BC:1F			                keyid:73:5F:60:D8:BC:CB:03:98:F4:2B:17:34:2E:36:5A:A6:60:FF:BC:1F
            Not After : Aug 22 17:08:50 2024 GMT							            Not After : Aug 22 17:08:50 2024 GMT
                keyid:73:5F:60:D8:BC:CB:03:98:F4:2B:17:34:2E:36:5A:A6:60:FF:BC:1F			                keyid:73:5F:60:D8:BC:CB:03:98:F4:2B:17:34:2E:36:5A:A6:60:FF:BC:1F
            Not After : Aug 22 17:08:50 2024 GMT							            Not After : Aug 22 17:08:50 2024 GMT
                keyid:73:5F:60:D8:BC:CB:03:98:F4:2B:17:34:2E:36:5A:A6:60:FF:BC:1F			                keyid:73:5F:60:D8:BC:CB:03:98:F4:2B:17:34:2E:36:5A:A6:60:FF:BC:1F
            Not After : Aug 22 17:08:50 2024 GMT						   <
                keyid:73:5F:60:D8:BC:CB:03:98:F4:2B:17:34:2E:36:5A:A6:60:FF:BC:1F		   <
            Not After : Aug 22 17:08:50 2024 GMT						   <
                keyid:73:5F:60:D8:BC:CB:03:98:F4:2B:17:34:2E:36:5A:A6:60:FF:BC:1F		   <
            Not After : Aug 22 17:08:50 2024 GMT						   <
                keyid:73:5F:60:D8:BC:CB:03:98:F4:2B:17:34:2E:36:5A:A6:60:FF:BC:1F		   <
            Not After : Aug 22 17:08:50 2024 GMT						   <
                keyid:73:5F:60:D8:BC:CB:03:98:F4:2B:17:34:2E:36:5A:A6:60:FF:BC:1F		   <
            Not After : Aug 22 17:08:50 2024 GMT						   <
                keyid:73:5F:60:D8:BC:CB:03:98:F4:2B:17:34:2E:36:5A:A6:60:FF:BC:1F		   <
            Not After : Aug 22 17:08:50 2024 GMT						   <
                keyid:73:5F:60:D8:BC:CB:03:98:F4:2B:17:34:2E:36:5A:A6:60:FF:BC:1F		   <
            Not After : Aug 22 17:08:50 2024 GMT						   <
                keyid:73:5F:60:D8:BC:CB:03:98:F4:2B:17:34:2E:36:5A:A6:60:FF:BC:1F		   <
            Not After : Aug 22 17:08:50 2024 GMT						   <
                keyid:73:5F:60:D8:BC:CB:03:98:F4:2B:17:34:2E:36:5A:A6:60:FF:BC:1F		   <
            Not After : Aug 22 17:08:50 2024 GMT						   <
                keyid:73:5F:60:D8:BC:CB:03:98:F4:2B:17:34:2E:36:5A:A6:60:FF:BC:1F		   <
            Not After : Aug 22 17:08:50 2024 GMT						   <
                keyid:73:5F:60:D8:BC:CB:03:98:F4:2B:17:34:2E:36:5A:A6:60:FF:BC:1F		   <
            Not After : Aug 22 17:08:50 2024 GMT						   <
                keyid:73:5F:60:D8:BC:CB:03:98:F4:2B:17:34:2E:36:5A:A6:60:FF:BC:1F		   <
            Not After : Aug 22 17:08:50 2024 GMT						   <
                keyid:73:5F:60:D8:BC:CB:03:98:F4:2B:17:34:2E:36:5A:A6:60:FF:BC:1F		   <
```

**Comment by richardTowers** [comment]
> I ran:
> 
> ```
> sdiff -w 200 <(openssl crl2pkcs7 -nocrl -certfile <(git show wip-tlwr:manifests/bosh-manifest/variables.yml  | boshfind -f - /aws_rds_combined_ca_bundle | tr -s '[[:space:]]' | sed 's/^ //' | tr -d "'" | grep .) | openssl pkcs7 -print_certs -text | grep -e keyid -e After) <(openssl crl2pkcs7 -nocrl -certfile <(git show master:manifests/bosh-manifest/variables.yml  | boshfind -f - /aws_rds_combined_ca_bundle | tr -s '[[:space:]]' | sed 's/^ //' | tr -d "'" | grep .) | openssl pkcs7 -print_certs -text | grep -e keyid -e After)
> ```

🤣  at this "one liner"

**Comment by tlwr** [comment]
This works in my environment, i.e. UAA and Credhub all come up ok with the new bundle

I'm going to clickops the bosh db in my dev env with the new bundle and see if it works.

**Comment by tlwr** [comment]
It works

merging and deploying

**Review by tlwr — APPROVED** [review]

**Pull request merged**
